services:
  - type: web
    name: goldtrack
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
